# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Next JS Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      

  sync-branch:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master

      - name: Merge Main into deploy
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: deploy
          message: 'Merges main into deploy'
          github_token: ${{ github.token }}